version: "3.5"
services:
  
  nginx:
    image: nginx:latest
    container_name: 'nginx10000'
    ports:
      - "10000:80"
    links:
      - swagger
    volumes:
      - /dru/default.conf:/etc/nginx/conf.d/default.conf
  swagger:
    image: swaggerapi/swagger-editor:latest
    container_name: swagger
    ports:
      - "10001:8080"
